"""Agregar columna imagen a la tabla cartas

Revision ID: 5082059703fd
Revises: 
Create Date: 2024-07-05 15:08:15.165137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5082059703fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('contraseña', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('confirmar_contraseña', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('foto', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.CheckConstraint('"confirmar_contraseña" = "contraseña"', name='chk_confirmacion_contraseña'),
    sa.PrimaryKeyConstraint('id', name='registro_pkey')
    )
    # ### end Alembic commands ###
